### ISSUE TITLE
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException

### ISSUE THREAD

**Issue by joconaut** [ollama4j/ollama4j#60]
Hi,
I talk to Ollama 0.3.0 using ollama4j 1.0.80. 

I receive an UnrecognizedPropertyException when I am doing

            OllamaAPI ollamaAPI = new OllamaAPI("...");
            ModelsProcessResponse mpr = ollamaAPI.ps();

I have llama3.1:latest running.

Here is the stacktrace:
------><---------------------------------------------
Unrecognized field "parent_model" (class io.github.ollama4j.models.ps.ModelsProcessResponse$ModelDetails), not marked as ignorable (6 known properties: "families", "quantizationLevel", "family", "format", "parameterSize", "parentModel"])
 at [Source: (String)"{"models":[{"name":"llama3.1:latest","model":"llama3.1:latest","size":6654289920,"digest":"62757c860e01d552d4e46b09c6b8d5396ef9015210105427e05a8b27d7727ed2","details":{"parent_model":"","format":"gguf","family":"llama","families":["llama"],"parameter_size":"8.0B","quantization_level":"Q4_0"},"expires_at":"2024-07-31T17:07:58.581961212+02:00","size_vram":6654289920}]}"; line: 1, column: 185] (through reference chain: io.github.ollama4j.models.ps.ModelsProcessResponse["models"]->java.util.ArrayList[0]->io.github.ollama4j.models.ps.ModelsProcessResponse$ModelProcess["details"]->io.github.ollama4j.models.ps.ModelsProcessResponse$ModelDetails["parent_model"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1138)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2224)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1709)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1687)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:320)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
        at io.github.ollama4j.OllamaAPI.ps(OllamaAPI.java:139)
        ....

Hope that helps. 

Best regards,
Joco

**Comment by amithkoujalgi** [comment]
@joconaut Thanks for reporting the issue!

[v1.0.82](https://github.com/ollama4j/ollama4j/tree/v1.0.82) fixes the issue. Also, be sure to update to the latest version of Ollama to keep things running smoothly.

Cheers!
