### ISSUE TITLE
Bug in OllamaChatEndpointCaller.parseResponseAndAddToBuffer

### ISSUE THREAD

**Issue by ilacc1** [ollama4j/ollama4j#78]
Under heavy usage, a NullPointerException is thrown in OllamaChatEndpointCaller.parseResponseAndAddToBuffer.

Relevant part of the stack:

```
java.lang.NullPointerException
	at io.github.ollama4j.models.request.OllamaChatEndpointCaller.parseResponseAndAddToBuffer(OllamaChatEndpointCaller.java:38)
	at io.github.ollama4j.models.request.OllamaEndpointCaller.callSync(OllamaEndpointCaller.java:95)
	at io.github.ollama4j.OllamaAPI.chat(OllamaAPI.java:775)
	at io.github.ollama4j.OllamaAPI.chat(OllamaAPI.java:750)

```
Offending code:

```
            OllamaChatResponseModel ollamaResponseModel = Utils.getObjectMapper().readValue(line, OllamaChatResponseModel.class);
            responseBuffer.append(ollamaResponseModel.getMessage().getContent());

```

It appears that `ollamaResponseModel` or `ollamaResponseModel.getMessage()` can be null in some circumstances which is not checked by the above code.

I found it difficult to reliably reproduce this and get to the bottom of which one of the two is null or why.

**Comment by AgentSchmecker** [comment]
@ilacc1 your issue should be solved via PR-#81

**Comment by almostobvious** [comment]
Hey thanks very much - didn't get a chance to test PR-#81 but I'm sure it's all sorted. Many thanks.
